# Generated by Django 5.2.8 on 2025-11-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='capture_image',
            field=models.ImageField(blank=True, null=True, upload_to='captured/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='used_low_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
