# Generated by Django 5.2.8 on 2025-11-09 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                (
                    "escrow_state",
                    models.CharField(
                        choices=[
                            ("HELD", "보관중"),
                            ("RELEASED", "지급완료"),
                            ("REFUNDED", "환불완료"),
                        ],
                        default="HELD",
                        max_length=16,
                    ),
                ),
                (
                    "confirmation_code",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="listings.listing",
                    ),
                ),
            ],
        ),
    ]
